Repository checkmarx-ltd/Cx-Client-Common, pull requests merged in 2020-07, with the labels that each got.

#51 increase time out for ossrh from 5min to 10min
  pom.xml
Labels: size/XS

#54 Added opensource readiness templates, readme, release notes generator
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  CONTRIBUTING.md
  README.md
Labels: size/L

#63 Updated the version to 2020.2.23
  pom.xml
Labels: size/XS

#65 New CI\CD pipeline
  Jenkinsfile-CI-CD
  pom.xml
Labels: size/L, skip-release-notes

#66 Fix GitHub Release
  Jenkinsfile-CI-CD
Labels: size/XS, skip-release-notes

#70 send data to elastic
  Jenkinsfile
  Jenkinsfile-CI-CD
Labels: size/L, skip-release-notes

#71 add auto versioning
  Jenkinsfile-CI-CD
Labels: size/S, skip-release-notes

#75 Eitanas1 change pom version
  Jenkinsfile-CI-CD
  pom.xml
Labels: size/XS, skip-release-notes
