Repository checkmarx-ltd/Cx-Client-Common, pull requests merged in 2020-08, with the labels that each got.

#74 Add CxSAST 9.3
  Jenkinsfile-CI-CD
Labels: size/M, skip-release-notes

#78 change default value for 9.3
  Jenkinsfile-CI-CD
Labels: size/XS, skip-release-notes

#80 increase decommissionPeriod to 2 hours
  Jenkinsfile-CI-CD
Labels: size/S, skip-release-notes

#81 add host to tests
  Jenkinsfile-CI-CD
Labels: size/S, skip-release-notes

#86 Update pom.xml with FSA version 20.0.5 since 20.0.7 is still not in m…
  pom.xml
Labels: size/XS

#89 use maven-central for build
  Jenkinsfile-CI-CD
Labels: size/S, skip-release-notes
