Repository checkmarx-ltd/Cx-Client-Common, pull requests merged in 2020-09, with the labels that each got.

#92 solve some problems in the checkmarx report tab, including AB#714
  src/main/resources/com/cx/report/report.ftl
Labels: size/S

#101 fix automationBranch for 1th run
  Jenkinsfile-CI-CD
Labels: size/XS, skip-release-notes

#103 Update pom.xml with new FSA version 20.0.8
  pom.xml
Labels: size/XS

#106 Publish cx artifactory
  Jenkinsfile-CI-CD
Labels: size/S, skip-release-notes
