Repository checkmarx-ltd/Cx-Client-Common, pull requests merged in 2024-07, with the labels that each got.

#254 Critical Severity
  src/main/java/com/cx/restclient/ast/AstSastClient.java
  src/main/java/com/cx/restclient/ast/AstScaClient.java
  src/main/java/com/cx/restclient/ast/dto/common/SummaryResults.java
  src/main/java/com/cx/restclient/ast/dto/sca/AstScaResults.java
  src/main/java/com/cx/restclient/ast/dto/sca/report/AstScaSummaryResults.java
  src/main/java/com/cx/restclient/ast/dto/sca/report/Package.java
  src/main/java/com/cx/restclient/ast/dto/sca/report/PackageSeverity.java
  src/main/java/com/cx/restclient/common/summary/DependencyScanResult.java
  src/main/java/com/cx/restclient/common/summary/SummaryUtils.java
  src/main/java/com/cx/restclient/configuration/CxScanConfig.java
  src/main/java/com/cx/restclient/dto/scansummary/ScanSummary.java
  src/main/java/com/cx/restclient/osa/dto/Library.java
  src/main/java/com/cx/restclient/osa/dto/OSAResults.java
  src/main/java/com/cx/restclient/osa/dto/OSASummaryResults.java
  src/main/java/com/cx/restclient/osa/dto/ScanConfiguration.java
  src/main/java/com/cx/restclient/osa/utils/OSAUtils.java
  src/main/resources/com/cx/report/report.ftl
  src/test/java/com/cx/restclient/general/ScaTestsBase.java
Labels: size/L

#255 Update Jenkinsfile-CI-CD
  Jenkinsfile-CI-CD
Labels: size/XS

#256 Revert "Update Jenkinsfile-CI-CD"
  Jenkinsfile-CI-CD
Labels: size/XS

#257 Update Jenkinsfile-CI-CD
  Jenkinsfile-CI-CD
Labels: size/XS

#258 Revert "Update Jenkinsfile-CI-CD"
  Jenkinsfile-CI-CD
Labels: size/XS

#259 SCA Critical Scan
  src/main/resources/com/cx/report/report.ftl
Labels: size/XS

#260 CLI PLUG 1906 and Critical severity related changes
  pom.xml
  src/main/java/com/cx/restclient/ast/AstScaClient.java
  src/main/java/com/cx/restclient/httpClient/CxHttpClient.java
  src/main/java/com/cx/restclient/sast/utils/SASTUtils.java
Labels: size/M

#261 PLUG 1931 and NONE severity related changes
  src/main/java/com/cx/restclient/configuration/CxScanConfig.java
  src/main/java/com/cx/restclient/dto/scansummary/Severity.java
  src/main/java/com/cx/restclient/httpClient/utils/ContentType.java
  src/main/java/com/cx/restclient/sast/dto/CreateBranchStatus.java
  src/main/java/com/cx/restclient/sast/dto/Status.java
  src/main/java/com/cx/restclient/sast/utils/LegacyClient.java
  src/main/java/com/cx/restclient/sast/utils/SASTParam.java
Labels: size/L

#262 Cli2024 q3 integration branch
  src/main/java/com/cx/restclient/ast/AstScaClient.java
  src/main/java/com/cx/restclient/common/summary/DependencyScanResult.java
  src/main/java/com/cx/restclient/configuration/CxScanConfig.java
  src/main/java/com/cx/restclient/dto/scansummary/ScanSummary.java
  src/main/java/com/cx/restclient/dto/scansummary/Severity.java
  src/main/java/com/cx/restclient/httpClient/CxHttpClient.java
  src/main/java/com/cx/restclient/httpClient/utils/ContentType.java
  src/main/java/com/cx/restclient/osa/dto/OSASummaryResults.java
  src/main/java/com/cx/restclient/osa/utils/OSAUtils.java
  src/main/java/com/cx/restclient/sast/dto/CreateBranchStatus.java
  src/main/java/com/cx/restclient/sast/dto/Status.java
  src/main/java/com/cx/restclient/sast/utils/LegacyClient.java
  src/main/java/com/cx/restclient/sast/utils/SASTParam.java
  src/main/java/com/cx/restclient/sast/utils/SASTUtils.java
  src/main/resources/com/cx/report/report.ftl
Labels: size/L

#264 check For Threshold Error
  src/main/java/com/cx/restclient/configuration/CxScanConfig.java
  src/main/java/com/cx/restclient/dto/scansummary/ScanSummary.java
Labels: size/S

#265 Ilan's Changes related to XML Report Generation (Bug-1782 and Bug-2025)
  pom.xml
  src/main/java/com/cx/restclient/CxSASTClient.java
  src/main/java/com/cx/restclient/common/Waiter.java
Labels: size/XL

#266 Revert "Ilan's Changes related to XML Report Generation (Bug-1782 and Bug-2025)"
  pom.xml
  src/main/java/com/cx/restclient/CxSASTClient.java
  src/main/java/com/cx/restclient/common/Waiter.java
Labels: size/XL
