Repository checkmarx-ltd/Cx-Client-Common, pull requests merged in 2025-07, with the labels that each got.

#278 2025 q3 integration branch
  src/main/java/com/cx/restclient/ast/AstScaClient.java
  src/main/java/com/cx/restclient/common/CxPARAM.java
  src/main/java/com/cx/restclient/httpClient/utils/HttpClientHelper.java
  src/main/java/com/cx/restclient/sca/dto/SbomReportResponse.java
  src/main/java/com/cx/restclient/sca/dto/ScanReportExportIdRequester.java
Labels: size/L

#279 Update Jenkinsfile-CI-CD
  Jenkinsfile-CI-CD
Labels: size/S

#280 deployment change from nexus to central
  Jenkinsfile-CI-CD
  pom.xml
Labels: size/L

#283 updated version to 3.11.0
  pom.xml
Labels: size/XS

#284 downgraded sonatype-plugin
  pom.xml
Labels: size/XS

#285 Pr downgrade sonatype pulgin
  pom.xml
Labels: size/XS

#286 Pr downgrade sonatype pulgin
  pom.xml
Labels: size/XS

#287 upgraded plugin
  pom.xml
Labels: size/XS

#290 Dockerize publish stage
  Jenkinsfile-CI-CD
Labels: size/XS
